import { Item, Project, Room } from "./types";

export const mockProject: Project = {
  id: "p1",
  title: "Project Renovation",
  totalBudget: 12500,
  currency: "EUR",
};

export const mockRooms: Room[] = [
  { id: "r1", type: "Baie", name: "Baie Principală", allocatedBudget: 1200 },
  { id: "r2", type: "Bucătărie", name: "Bucătărie", allocatedBudget: 3500 },
  { id: "r3", type: "Living", name: "Living & Dining", allocatedBudget: 4800 },
  { id: "r4", type: "Dormitor", name: "Dormitor Matrimonial", allocatedBudget: 2000 },
];

export const mockItems: Item[] = [
  {
    id: "i1",
    roomId: "r1",
    name: "Robinet Chrome",
    materialType: "Sanitare",
    source: "Dedeman",
    status: "Cumpărat",
    quantity: 1,
    unitPrice: 215,
  },
  {
    id: "i2",
    roomId: "r1",
    name: "Oglindă LED Smart",
    materialType: "Sanitare",
    source: "Hornbach",
    status: "Planificat",
    quantity: 1,
    unitPrice: 185,
  },
  {
    id: "i3",
    roomId: "r1",
    name: "Cadă Freestanding",
    materialType: "Sanitare",
    source: "Westag",
    status: "În așteptare",
    quantity: 1,
    unitPrice: 890,
  },
  {
    id: "i4",
    roomId: "r2",
    name: "Frigider Side-by-Side",
    materialType: "Electrocasnice",
    source: "Altex",
    status: "Cumpărat",
    quantity: 1,
    unitPrice: 1800,
  },
  {
    id: "i5",
    roomId: "r2",
    name: "Mașină de Spălat Vase",
    materialType: "Electrocasnice",
    source: "eMAG",
    status: "Cumpărat",
    quantity: 1,
    unitPrice: 650,
  },
  {
    id: "i6",
    roomId: "r2",
    name: "Mobilier MDF Vopsit la Comandă",
    materialType: "Mobilă",
    source: "Vanguard",
    status: "În așteptare",
    quantity: 1,
    unitPrice: 3200,
  },
  {
    id: "i7",
    roomId: "r3",
    name: "Parchet Triplustratificat Stejar",
    materialType: "Parchet",
    source: "Tarkett S.A.",
    status: "Cumpărat",
    quantity: 45,
    unitPrice: 12,
  },
  {
    id: "i8",
    roomId: "r3",
    name: "Canapea Modulară Velvet",
    materialType: "Mobilă",
    source: "The Home",
    status: "În așteptare",
    quantity: 1,
    unitPrice: 1400,
  },
  {
    id: "i9",
    roomId: "r3",
    name: "Chiuvetă Granit + Baterie Extensibilă",
    materialType: "Sanitare",
    source: "Franke",
    status: "Cumpărat",
    quantity: 1,
    unitPrice: 380,
  },
  {
    id: "i10",
    roomId: "r4",
    name: "Corp Iluminat Suspendat",
    materialType: "Corpuri de iluminat",
    source: "IKEA",
    status: "Planificat",
    quantity: 2,
    unitPrice: 95,
  },
];
