import {
  Currency,
  FlooringType,
  InstallationType,
  Item,
  ItemStatus,
  MaterialType,
  Project,
  Room,
  RoomType,
  TileSize,
  Wall,
} from "./types";

export const mockProject: Project = {
  id: "p1",
  title: "Apartament 3 Camere - Pipera",
  totalBudget: 12500,
  currency: Currency.EUR,
};

export const mockRooms: Room[] = [
  {
    id: "r1",
    type: RoomType.Baie,
    name: "Baie Principală",
    allocatedBudget: 1200,
    floorMaterial: FlooringType.Gresie,
    floorArea: 5.4,
    perimeter: 9.3,
    tileSize: TileSize.Medie,
    installationType: InstallationType.Drept,
    door: { width: 0.8, height: 2.1, wall: Wall.Vest },
    wallTiling: {
      tiledWallsCount: 3,
      tileHeight: 2.4,
      wallLengths: { [Wall.Nord]: 2.4, [Wall.Est]: 2.25, [Wall.Sud]: 2.4, [Wall.Vest]: 2.25 },
    },
  },
  { id: "r2", type: RoomType.Bucatarie, name: "Bucătărie", allocatedBudget: 3500 },
  {
    id: "r3",
    type: RoomType.Living,
    name: "Living & Dining",
    allocatedBudget: 4800,
    floorMaterial: FlooringType.ParchetLaminat,
    floorArea: 27.3,
    perimeter: 21,
    tileSize: TileSize.Medie,
    installationType: InstallationType.Drept,
    door: { width: 0.9, height: 2.1, wall: Wall.Nord },
  },
  { id: "r4", type: RoomType.Dormitor, name: "Dormitor Matrimonial", allocatedBudget: 2000 },
];

export const mockItems: Item[] = [
  {
    id: "i1",
    roomId: "r1",
    name: "Robinet Chrome",
    materialType: MaterialType.Sanitare,
    source: "Dedeman",
    status: ItemStatus.Cumparat,
    quantity: 1,
    unitPrice: 215,
  },
  {
    id: "i2",
    roomId: "r1",
    name: "Oglindă LED Smart",
    materialType: MaterialType.Sanitare,
    source: "Hornbach",
    status: ItemStatus.Planificat,
    quantity: 1,
    unitPrice: 185,
  },
  {
    id: "i3",
    roomId: "r1",
    name: "Cadă Freestanding",
    materialType: MaterialType.Sanitare,
    source: "Westag",
    status: ItemStatus.InAsteptare,
    quantity: 1,
    unitPrice: 890,
  },
  {
    id: "i4",
    roomId: "r2",
    name: "Frigider Side-by-Side",
    materialType: MaterialType.Electrocasnice,
    source: "Altex",
    status: ItemStatus.Cumparat,
    quantity: 1,
    unitPrice: 1800,
  },
  {
    id: "i5",
    roomId: "r2",
    name: "Mașină de Spălat Vase",
    materialType: MaterialType.Electrocasnice,
    source: "eMAG",
    status: ItemStatus.Cumparat,
    quantity: 1,
    unitPrice: 650,
  },
  {
    id: "i6",
    roomId: "r2",
    name: "Mobilier MDF Vopsit la Comandă",
    materialType: MaterialType.Mobila,
    source: "Vanguard",
    status: ItemStatus.InAsteptare,
    quantity: 1,
    unitPrice: 3200,
  },
  {
    id: "i7",
    roomId: "r3",
    name: "Parchet Triplustratificat Stejar",
    materialType: MaterialType.Parchet,
    source: "Tarkett S.A.",
    status: ItemStatus.Cumparat,
    quantity: 45,
    unitPrice: 12,
  },
  {
    id: "i8",
    roomId: "r3",
    name: "Canapea Modulară Velvet",
    materialType: MaterialType.Mobila,
    source: "The Home",
    status: ItemStatus.InAsteptare,
    quantity: 1,
    unitPrice: 1400,
  },
  {
    id: "i9",
    roomId: "r3",
    name: "Chiuvetă Granit + Baterie Extensibilă",
    materialType: MaterialType.Sanitare,
    source: "Franke",
    status: ItemStatus.Cumparat,
    quantity: 1,
    unitPrice: 380,
  },
  {
    id: "i10",
    roomId: "r4",
    name: "Corp Iluminat Suspendat",
    materialType: MaterialType.CorpuriIluminat,
    source: "IKEA",
    status: ItemStatus.Planificat,
    quantity: 2,
    unitPrice: 95,
  },
];
